version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
