import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/** Shorthand for a doc ref (doc already claimed by docsSidebar) */
const ref = (id: string) => ({type: 'ref' as const, id});

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Fundamentals',
      collapsed: true,
      items: [
        'intro',
        'fundamentals/index',
        'fundamentals/machine-learning',
        'fundamentals/deep-learning',
      ],
    },
    {
      type: 'category',
      label: 'Neural Networks',
      collapsed: true,
      items: ['neural-networks/index', 'neural-networks/cnn', 'neural-networks/rnn'],
    },
    {
      type: 'category',
      label: 'Transformers',
      collapsed: true,
      items: ['transformers/index', 'transformers/bert', 'transformers/gpt'],
    },
    {
      type: 'category',
      label: 'Large Language Models (LLMs)',
      collapsed: true,
      items: [
        'llms/index',
        'llms/fine-tuning',
        'llms/streaming',
      ],
    },
    {
      type: 'category',
      label: 'Prompt Engineering',
      collapsed: true,
      items: [
        'prompt-engineering/index',
        'prompt-engineering/temperature-top-k-top-p',
        'prompt-engineering/max-tokens-stop-sequences',
        'prompt-engineering/structured-outputs',
        'prompt-engineering/system-role-contextual-prompting',
        'prompt-engineering/self-consistency',
        'prompt-engineering/step-back-prompting',
        'prompt-engineering/automatic-prompt-engineering',
        'prompt-engineering/debiasing-techniques',
        'prompt-engineering/prompt-ensembling',
        'prompt-engineering/self-evaluation-calibration',
      ],
    },
    {
      type: 'category',
      label: 'Model Providers',
      collapsed: true,
      items: [
        'model-providers/index',
        'model-providers/openai',
        'model-providers/anthropic',
        'model-providers/google-gemini',
        'model-providers/meta-llama',
        'model-providers/mistral',
        'model-providers/cohere',
        'model-providers/deepseek',
      ],
    },
    {
      type: 'category',
      label: 'Retrieval & RAG',
      collapsed: true,
      items: [
        'rag/index',
        'rag/architecture',
        'rag/examples',
        'rag/vector-databases',
        'rag/embeddings',
      ],
    },
    {
      type: 'category',
      label: 'AI Agents & Systems',
      collapsed: true,
      items: [
        'agents/index',
        'agents/multi-agent-systems',
        'subagents/index',
        'autonomous-agents/index',
        {
          type: 'category',
          label: 'Memory',
          collapsed: true,
          items: [
            'agents/memory',
            'agents/conversational-memory',
          ],
        },
        {
          type: 'category',
          label: 'Architectures',
          collapsed: true,
          items: [
            'agents/planner-executor',
            'agents/dag-agents',
            'agents/self-critique',
            'agents/tools-actions',
          ],
        },
        {
          type: 'category',
          label: 'Agent Frameworks',
          collapsed: true,
          items: [
            'agents/frameworks-overview',
            'agents/crewai',
            'agents/autogen',
            'agents/langgraph',
            'agents/anthropic-tool-use',
          ],
        },
        {
          type: 'category',
          label: 'Evaluation & Ops',
          collapsed: true,
          items: [
            'agents/evaluation',
            'agents/debugging',
            'agents/security',
            'agents/prompt-engineering',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Model Context Protocol (MCP)',
      collapsed: true,
      items: [
        'mcp/index',
        'mcp/building-servers',
        'mcp/building-clients',
      ],
    },
    {
      type: 'category',
      label: 'Reasoning Patterns',
      collapsed: true,
      items: [
        'reasoning-patterns/index',
        'reasoning-patterns/cot',
        'reasoning-patterns/tot',
        'reasoning-patterns/react',
        'reasoning-patterns/rdd',
      ],
    },
    {
      type: 'category',
      label: 'Development Approaches',
      collapsed: true,
      items: ['spec-driven-development/index', 'vibe-coding'],
    },
    {
      type: 'category',
      label: 'AI Safety & Ethics',
      collapsed: true,
      items: [
        'ai-safety/index',
        'bias-in-ai/index',
        'xai/index',
        'ai-ethics/index',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Learning',
      collapsed: true,
      items: [
        'rl/index',
        'drl/index',
        'gans/index',
        'diffusion-models/index',
        'vaes/index',
        'federated-learning/index',
        'transfer-learning/index',
        'few-shot-learning/index',
        'zero-shot-learning/index',
      ],
    },
    {
      type: 'category',
      label: 'Fields in AI',
      collapsed: true,
      items: [
        'nlp/index',
        'cv/index',
        'speech-recognition/index',
        'ai-robotics/index',
        'multimodal-ai/index',
        'semantic-search/index',
      ],
    },
    {
      type: 'category',
      label: 'Evaluation & Benchmarks',
      collapsed: true,
      items: ['evaluation-metrics/index', 'benchmarks/index'],
    },
    {
      type: 'category',
      label: 'Tools & Ecosystem',
      collapsed: true,
      items: [
        'tools/huggingface',
        'tools/langchain',
        'tools/llamaindex',
        'tools/cursor',
        'tools/github-copilot',
        'tools/claude-code',
        'tools/antigravity',
        'tools/kiro',
        {
          type: 'category',
          label: 'Claude Code Deep Dive',
          collapsed: true,
          items: [
            'claude-code/index',
            'claude-code/claude-md',
            'claude-code/skills',
            'claude-code/thinking-modes',
            'claude-code/prompt-caching',
            'claude-code/context-management',
            'claude-code/mcp-plugins',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'MLOps',
      collapsed: true,
      items: [
        'mlops/index',
        'mlops/experiment-tracking',
        'mlops/mlflow',
        'mlops/wandb',
        'mlops/feature-stores',
        {
          type: 'category',
          label: 'Data Engineering',
          collapsed: true,
          items: [
            'mlops/data-engineering/index',
            'mlops/data-engineering/airflow',
            'mlops/data-engineering/spark',
            'mlops/data-engineering/kafka',
          ],
        },
        {
          type: 'category',
          label: 'CI/CD & Versioning',
          collapsed: true,
          items: [
            'mlops/cicd/index',
            'mlops/cicd/dvc',
            'mlops/cicd/model-registry',
          ],
        },
        {
          type: 'category',
          label: 'Deployment & Serving',
          collapsed: true,
          items: [
            'mlops/deployment/model-serving',
            'mlops/deployment/kubeflow',
            'mlops/deployment/ml-kubernetes',
          ],
        },
        {
          type: 'category',
          label: 'Monitoring',
          collapsed: true,
          items: [
            'mlops/monitoring/index',
            'mlops/monitoring/prometheus',
            'mlops/monitoring/grafana',
          ],
        },
        {
          type: 'category',
          label: 'Infrastructure as Code',
          collapsed: true,
          items: [
            'mlops/iac/terraform',
            'mlops/iac/ansible',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [
        'infrastructure/index',
        'local-inference/index',
        'edge-reasoning/index',
        'model-compression/index',
        'quantization/index',
        'pruning/index',
        'knowledge-distillation/index',
        {
          type: 'category',
          label: 'Edge AI',
          collapsed: true,
          items: [
            'edge-ai/tflite',
            'edge-ai/pytorch-mobile',
            'edge-ai/onnx',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      collapsed: true,
      items: ['frameworks/tensorflow', 'frameworks/pytorch'],
    },
    {
      type: 'category',
      label: 'Case Studies',
      collapsed: true,
      items: [
        'case-studies/chatgpt',
        'case-studies/dall-e',
        'case-studies/claude',
        'case-studies/gemini',
        'case-studies/bart',
        'case-studies/grok',
        'case-studies/deepseek',
        'case-studies/qwen',
      ],
    },
    'glossary',
    'changelog',
  ],

  // Learning Path 1: AI Fundamentals (beginner)
  aiFundamentals: [
    {
      type: 'category',
      label: 'AI Fundamentals',
      collapsed: false,
      items: [
        ref('intro'),
        ref('fundamentals/index'),
        ref('fundamentals/machine-learning'),
        ref('fundamentals/deep-learning'),
        ref('neural-networks/index'),
        ref('neural-networks/cnn'),
        ref('neural-networks/rnn'),
        ref('transformers/index'),
        ref('transformers/bert'),
        ref('transformers/gpt'),
        ref('llms/index'),
        ref('nlp/index'),
        ref('cv/index'),
        ref('glossary'),
      ],
    },
  ],

  // Learning Path 2: RAG from Zero (beginner → intermediate)
  ragFromZero: [
    {
      type: 'category',
      label: 'RAG from Zero',
      collapsed: false,
      items: [
        ref('llms/index'),
        ref('prompt-engineering/index'),
        ref('prompt-engineering/system-role-contextual-prompting'),
        ref('prompt-engineering/temperature-top-k-top-p'),
        ref('prompt-engineering/structured-outputs'),
        ref('semantic-search/index'),
        ref('rag/index'),
        ref('rag/embeddings'),
        ref('rag/vector-databases'),
        ref('rag/architecture'),
        ref('rag/examples'),
        ref('model-providers/openai'),
        ref('model-providers/cohere'),
        ref('tools/langchain'),
        ref('tools/llamaindex'),
      ],
    },
  ],

  // Learning Path 3: Mastering Agents (intermediate → advanced)
  masteringAgents: [
    {
      type: 'category',
      label: 'Mastering Agents',
      collapsed: false,
      items: [
        ref('agents/index'),
        ref('reasoning-patterns/cot'),
        ref('reasoning-patterns/react'),
        ref('agents/tools-actions'),
        ref('agents/memory'),
        ref('agents/conversational-memory'),
        ref('agents/planner-executor'),
        ref('agents/dag-agents'),
        ref('agents/self-critique'),
        ref('agents/multi-agent-systems'),
        ref('subagents/index'),
        ref('agents/frameworks-overview'),
        ref('agents/langgraph'),
        ref('agents/crewai'),
        ref('agents/autogen'),
        ref('agents/anthropic-tool-use'),
        ref('agents/evaluation'),
        ref('agents/debugging'),
        ref('agents/security'),
        ref('mcp/index'),
        ref('mcp/building-servers'),
        ref('mcp/building-clients'),
      ],
    },
  ],

  // Learning Path 4: Prompt Engineering Mastery (beginner → advanced)
  promptEngineeringMastery: [
    {
      type: 'category',
      label: 'Prompt Engineering Mastery',
      collapsed: false,
      items: [
        ref('prompt-engineering/index'),
        ref('prompt-engineering/system-role-contextual-prompting'),
        ref('prompt-engineering/temperature-top-k-top-p'),
        ref('prompt-engineering/max-tokens-stop-sequences'),
        ref('prompt-engineering/structured-outputs'),
        ref('reasoning-patterns/cot'),
        ref('reasoning-patterns/tot'),
        ref('prompt-engineering/self-consistency'),
        ref('prompt-engineering/step-back-prompting'),
        ref('prompt-engineering/prompt-ensembling'),
        ref('prompt-engineering/debiasing-techniques'),
        ref('prompt-engineering/self-evaluation-calibration'),
        ref('prompt-engineering/automatic-prompt-engineering'),
      ],
    },
  ],

  // Learning Path 5: Practical MLOps (intermediate → advanced)
  practicalMlops: [
    {
      type: 'category',
      label: 'Practical MLOps',
      collapsed: false,
      items: [
        ref('mlops/index'),
        ref('mlops/experiment-tracking'),
        ref('mlops/mlflow'),
        ref('mlops/wandb'),
        ref('mlops/feature-stores'),
        ref('mlops/data-engineering/index'),
        ref('mlops/data-engineering/airflow'),
        ref('mlops/data-engineering/spark'),
        ref('mlops/data-engineering/kafka'),
        ref('mlops/cicd/index'),
        ref('mlops/cicd/dvc'),
        ref('mlops/cicd/model-registry'),
        ref('mlops/deployment/model-serving'),
        ref('mlops/deployment/kubeflow'),
        ref('mlops/deployment/ml-kubernetes'),
        ref('mlops/monitoring/index'),
        ref('mlops/monitoring/prometheus'),
        ref('mlops/monitoring/grafana'),
        ref('mlops/iac/terraform'),
        ref('mlops/iac/ansible'),
      ],
    },
  ],

  // Learning Path 6: AI Tools & Frameworks (beginner → intermediate)
  aiToolsFrameworks: [
    {
      type: 'category',
      label: 'AI Tools & Frameworks',
      collapsed: false,
      items: [
        ref('model-providers/index'),
        ref('model-providers/openai'),
        ref('model-providers/anthropic'),
        ref('model-providers/google-gemini'),
        ref('model-providers/meta-llama'),
        ref('model-providers/mistral'),
        ref('model-providers/cohere'),
        ref('model-providers/deepseek'),
        ref('frameworks/pytorch'),
        ref('frameworks/tensorflow'),
        ref('tools/huggingface'),
        ref('tools/langchain'),
        ref('tools/llamaindex'),
        ref('tools/cursor'),
        ref('tools/github-copilot'),
        ref('tools/claude-code'),
      ],
    },
  ],

  // Learning Path 7: AI Safety & Ethics (beginner → intermediate)
  aiSafetyEthics: [
    {
      type: 'category',
      label: 'AI Safety & Ethics',
      collapsed: false,
      items: [
        ref('ai-safety/index'),
        ref('ai-ethics/index'),
        ref('bias-in-ai/index'),
        ref('xai/index'),
        ref('prompt-engineering/debiasing-techniques'),
        ref('agents/security'),
        ref('agents/evaluation'),
      ],
    },
  ],

  // Learning Path 8: Claude Code Deep Dive (beginner → advanced)
  claudeCodeDeepDive: [
    {
      type: 'category',
      label: 'Claude Code Deep Dive',
      collapsed: false,
      items: [
        ref('tools/claude-code'),
        ref('claude-code/index'),
        ref('claude-code/claude-md'),
        ref('claude-code/skills'),
        ref('claude-code/thinking-modes'),
        ref('claude-code/prompt-caching'),
        ref('claude-code/context-management'),
        ref('claude-code/mcp-plugins'),
        ref('mcp/index'),
        ref('mcp/building-servers'),
        ref('mcp/building-clients'),
        ref('model-providers/anthropic'),
      ],
    },
  ],
};

export default sidebars;
