import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Fundamentals',
      collapsed: true,
      items: [
        'intro',
        'fundamentals/index',
        'fundamentals/machine-learning',
        'fundamentals/deep-learning',
      ],
    },
    {
      type: 'category',
      label: 'Neural Networks',
      collapsed: true,
      items: ['neural-networks/index', 'neural-networks/cnn', 'neural-networks/rnn'],
    },
    {
      type: 'category',
      label: 'Transformers',
      collapsed: true,
      items: ['transformers/index', 'transformers/bert', 'transformers/gpt'],
    },
    {
      type: 'category',
      label: 'Large Language Models (LLMs)',
      collapsed: true,
      items: [
        'llms/index',
        'llms/fine-tuning',
        'llms/streaming',
      ],
    },
    {
      type: 'category',
      label: 'Prompt Engineering',
      collapsed: true,
      items: [
        'prompt-engineering/index',
        'prompt-engineering/temperature-top-k-top-p',
        'prompt-engineering/max-tokens-stop-sequences',
        'prompt-engineering/structured-outputs',
        'prompt-engineering/system-role-contextual-prompting',
        'prompt-engineering/self-consistency',
        'prompt-engineering/step-back-prompting',
        'prompt-engineering/automatic-prompt-engineering',
        'prompt-engineering/debiasing-techniques',
        'prompt-engineering/prompt-ensembling',
        'prompt-engineering/self-evaluation-calibration',
      ],
    },
    {
      type: 'category',
      label: 'Retrieval & RAG',
      collapsed: true,
      items: [
        'rag/index',
        'rag/architecture',
        'rag/examples',
        'rag/vector-databases',
        'rag/embeddings',
      ],
    },
    {
      type: 'category',
      label: 'AI Agents & Systems',
      collapsed: true,
      items: [
        'agents/index',
        'agents/multi-agent-systems',
        'subagents/index',
        'autonomous-agents/index',
        {
          type: 'category',
          label: 'Memory',
          collapsed: true,
          items: [
            'agents/memory',
            'agents/conversational-memory',
          ],
        },
        {
          type: 'category',
          label: 'Architectures',
          collapsed: true,
          items: [
            'agents/planner-executor',
            'agents/dag-agents',
            'agents/self-critique',
            'agents/tools-actions',
          ],
        },
        {
          type: 'category',
          label: 'Agent Frameworks',
          collapsed: true,
          items: [
            'agents/frameworks-overview',
            'agents/crewai',
            'agents/autogen',
            'agents/langgraph',
            'agents/anthropic-tool-use',
          ],
        },
        {
          type: 'category',
          label: 'Evaluation & Ops',
          collapsed: true,
          items: [
            'agents/evaluation',
            'agents/debugging',
            'agents/security',
            'agents/prompt-engineering',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reasoning Patterns',
      collapsed: true,
      items: [
        'reasoning-patterns/index',
        'reasoning-patterns/cot',
        'reasoning-patterns/tot',
        'reasoning-patterns/react',
        'reasoning-patterns/rdd',
      ],
    },
    {
      type: 'category',
      label: 'Development Approaches',
      collapsed: true,
      items: ['spec-driven-development/index', 'vibe-coding'],
    },
    {
      type: 'category',
      label: 'AI Safety & Ethics',
      collapsed: true,
      items: [
        'ai-safety/index',
        'bias-in-ai/index',
        'xai/index',
        'ai-ethics/index',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Learning',
      collapsed: true,
      items: [
        'rl/index',
        'drl/index',
        'gans/index',
        'diffusion-models/index',
        'vaes/index',
        'federated-learning/index',
        'transfer-learning/index',
        'few-shot-learning/index',
        'zero-shot-learning/index',
      ],
    },
    {
      type: 'category',
      label: 'Fields in AI',
      collapsed: true,
      items: [
        'nlp/index',
        'cv/index',
        'speech-recognition/index',
        'ai-robotics/index',
        'multimodal-ai/index',
        'semantic-search/index',
      ],
    },
    {
      type: 'category',
      label: 'Evaluation & Benchmarks',
      collapsed: true,
      items: ['evaluation-metrics/index', 'benchmarks/index'],
    },
    {
      type: 'category',
      label: 'Tools & Ecosystem',
      collapsed: true,
      items: [
        'tools/huggingface',
        'tools/langchain',
        'tools/llamaindex',
        'tools/cursor',
        'tools/github-copilot',
        'tools/claude-code',
        'tools/antigravity',
        'tools/kiro',
      ],
    },
    {
      type: 'category',
      label: 'MLOps',
      collapsed: true,
      items: [
        'mlops/index',
        'mlops/experiment-tracking',
        'mlops/mlflow',
        'mlops/wandb',
        'mlops/feature-stores',
        {
          type: 'category',
          label: 'Data Engineering',
          collapsed: true,
          items: [
            'mlops/data-engineering/index',
            'mlops/data-engineering/airflow',
            'mlops/data-engineering/spark',
            'mlops/data-engineering/kafka',
          ],
        },
        {
          type: 'category',
          label: 'CI/CD & Versioning',
          collapsed: true,
          items: [
            'mlops/cicd/index',
            'mlops/cicd/dvc',
            'mlops/cicd/model-registry',
          ],
        },
        {
          type: 'category',
          label: 'Deployment & Serving',
          collapsed: true,
          items: [
            'mlops/deployment/model-serving',
            'mlops/deployment/kubeflow',
            'mlops/deployment/ml-kubernetes',
          ],
        },
        {
          type: 'category',
          label: 'Monitoring',
          collapsed: true,
          items: [
            'mlops/monitoring/index',
            'mlops/monitoring/prometheus',
            'mlops/monitoring/grafana',
          ],
        },
        {
          type: 'category',
          label: 'Infrastructure as Code',
          collapsed: true,
          items: [
            'mlops/iac/terraform',
            'mlops/iac/ansible',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [
        'infrastructure/index',
        'local-inference/index',
        'edge-reasoning/index',
        'model-compression/index',
        'quantization/index',
        'pruning/index',
        'knowledge-distillation/index',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      collapsed: true,
      items: ['frameworks/tensorflow', 'frameworks/pytorch'],
    },
    {
      type: 'category',
      label: 'Case Studies',
      collapsed: true,
      items: [
        'case-studies/chatgpt',
        'case-studies/dall-e',
        'case-studies/claude',
        'case-studies/gemini',
        'case-studies/bart',
        'case-studies/grok',
        'case-studies/deepseek',
        'case-studies/qwen',
      ],
    },
    'glossary',
    'changelog',
  ],
};

export default sidebars;
