import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Fundamentals',
      collapsed: true,
      items: [
        'intro',
        'fundamentals/index',
        'fundamentals/machine-learning',
        'fundamentals/deep-learning',
      ],
    },
    {
      type: 'category',
      label: 'Neural Networks',
      collapsed: true,
      items: ['neural-networks/index', 'neural-networks/cnn', 'neural-networks/rnn'],
    },
    {
      type: 'category',
      label: 'Transformers',
      collapsed: true,
      items: ['transformers/index', 'transformers/bert', 'transformers/gpt'],
    },
    {
      type: 'category',
      label: 'Large Language Models (LLMs)',
      collapsed: true,
      items: [
        'llms/index',
        'llms/fine-tuning',
        'llms/prompt-engineering',
        'llms/streaming',
      ],
    },
    {
      type: 'category',
      label: 'Retrieval & RAG',
      collapsed: true,
      items: [
        'rag/index',
        'rag/architecture',
        'rag/examples',
        'rag/vector-databases',
        'rag/embeddings',
      ],
    },
    {
      type: 'category',
      label: 'AI Agents & Systems',
      collapsed: true,
      items: [
        'agents/index',
        'agents/multi-agent-systems',
        'subagents/index',
        'autonomous-agents/index',
      ],
    },
    {
      type: 'category',
      label: 'Reasoning Patterns',
      collapsed: true,
      items: [
        'reasoning-patterns/index',
        'reasoning-patterns/cot',
        'reasoning-patterns/tot',
        'reasoning-patterns/react',
        'reasoning-patterns/rdd',
      ],
    },
    {
      type: 'category',
      label: 'Development Approaches',
      collapsed: true,
      items: ['spec-driven-development/index', 'vibe-coding'],
    },
    {
      type: 'category',
      label: 'AI Safety & Ethics',
      collapsed: true,
      items: [
        'ai-safety/index',
        'bias-in-ai/index',
        'xai/index',
        'ai-ethics/index',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Learning',
      collapsed: true,
      items: [
        'rl/index',
        'drl/index',
        'gans/index',
        'diffusion-models/index',
        'vaes/index',
        'federated-learning/index',
        'transfer-learning/index',
        'few-shot-learning/index',
        'zero-shot-learning/index',
      ],
    },
    {
      type: 'category',
      label: 'Fields in AI',
      collapsed: true,
      items: [
        'nlp/index',
        'cv/index',
        'speech-recognition/index',
        'ai-robotics/index',
        'multimodal-ai/index',
        'semantic-search/index',
      ],
    },
    {
      type: 'category',
      label: 'Evaluation & Benchmarks',
      collapsed: true,
      items: ['evaluation-metrics/index', 'benchmarks/index'],
    },
    {
      type: 'category',
      label: 'Tools & Ecosystem',
      collapsed: true,
      items: [
        'tools/huggingface',
        'tools/langchain',
        'tools/llamaindex',
        'tools/cursor',
        'tools/github-copilot',
        'tools/claude-code',
        'tools/antigravity',
        'tools/kiro',
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [
        'infrastructure/index',
        'local-inference/index',
        'edge-reasoning/index',
        'model-compression/index',
        'quantization/index',
        'pruning/index',
        'knowledge-distillation/index',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      collapsed: true,
      items: ['frameworks/tensorflow', 'frameworks/pytorch'],
    },
    {
      type: 'category',
      label: 'Case Studies',
      collapsed: true,
      items: [
        'case-studies/chatgpt',
        'case-studies/dall-e',
        'case-studies/claude',
        'case-studies/gemini',
        'case-studies/bart',
        'case-studies/grok',
        'case-studies/deepseek',
        'case-studies/qwen',
      ],
    },
    'glossary',
    'changelog',
  ],
};

export default sidebars;
